// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ipsecvpntunnel.proto

package model

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// IPSecVpnTunnel is used to store definition of a sase config as a k8s CRD resource.
type IPSecVpnTunnel struct {
	// TunnelName
	TunnelName string `protobuf:"bytes,1,opt,name=tunnel_name,json=tunnelName,proto3" json:"tunnel_name,omitempty"`
	// Tunnel Destination IP
	TunnelDestinationIp string `protobuf:"bytes,2,opt,name=tunnel_destination_ip,json=tunnelDestinationIp,proto3" json:"tunnel_destination_ip,omitempty"`
	// Tunnel Source IP
	TunnelSourceIp string `protobuf:"bytes,3,opt,name=tunnel_source_ip,json=tunnelSourceIp,proto3" json:"tunnel_source_ip,omitempty"`
	// Security Parameters for the tunnel
	SecurityAssociation  string   `protobuf:"bytes,4,opt,name=security_association,json=securityAssociation,proto3" json:"security_association,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPSecVpnTunnel) Reset()         { *m = IPSecVpnTunnel{} }
func (m *IPSecVpnTunnel) String() string { return proto.CompactTextString(m) }
func (*IPSecVpnTunnel) ProtoMessage()    {}
func (*IPSecVpnTunnel) Descriptor() ([]byte, []int) {
	return fileDescriptor_a40b6333f3796605, []int{0}
}
func (m *IPSecVpnTunnel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPSecVpnTunnel.Unmarshal(m, b)
}
func (m *IPSecVpnTunnel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPSecVpnTunnel.Marshal(b, m, deterministic)
}
func (m *IPSecVpnTunnel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPSecVpnTunnel.Merge(m, src)
}
func (m *IPSecVpnTunnel) XXX_Size() int {
	return xxx_messageInfo_IPSecVpnTunnel.Size(m)
}
func (m *IPSecVpnTunnel) XXX_DiscardUnknown() {
	xxx_messageInfo_IPSecVpnTunnel.DiscardUnknown(m)
}

var xxx_messageInfo_IPSecVpnTunnel proto.InternalMessageInfo

func (m *IPSecVpnTunnel) GetTunnelName() string {
	if m != nil {
		return m.TunnelName
	}
	return ""
}

func (m *IPSecVpnTunnel) GetTunnelDestinationIp() string {
	if m != nil {
		return m.TunnelDestinationIp
	}
	return ""
}

func (m *IPSecVpnTunnel) GetTunnelSourceIp() string {
	if m != nil {
		return m.TunnelSourceIp
	}
	return ""
}

func (m *IPSecVpnTunnel) GetSecurityAssociation() string {
	if m != nil {
		return m.SecurityAssociation
	}
	return ""
}

func init() {
	proto.RegisterType((*IPSecVpnTunnel)(nil), "model.IPSecVpnTunnel")
}

func init() { proto.RegisterFile("ipsecvpntunnel.proto", fileDescriptor_a40b6333f3796605) }

var fileDescriptor_a40b6333f3796605 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x41, 0xca, 0xc2, 0x30,
	0x10, 0x46, 0xe9, 0xff, 0xab, 0xe0, 0x08, 0x45, 0x62, 0x85, 0xee, 0x14, 0x57, 0x5d, 0x09, 0xea,
	0x09, 0x04, 0x37, 0xdd, 0x88, 0x58, 0x71, 0x5b, 0x62, 0x3a, 0x8b, 0x40, 0x3b, 0x19, 0x9a, 0x54,
	0xf0, 0x7a, 0x9e, 0x4c, 0x4c, 0x2a, 0xdd, 0xbe, 0xf7, 0xe6, 0x83, 0x81, 0x44, 0xb3, 0x45, 0xf5,
	0x64, 0x72, 0x1d, 0x11, 0xd6, 0x5b, 0x6e, 0x8d, 0x33, 0x62, 0xdc, 0x98, 0x0a, 0xeb, 0xcd, 0x3b,
	0x82, 0x38, 0xbf, 0x14, 0xa8, 0xee, 0x4c, 0x37, 0xef, 0xc5, 0x0a, 0x66, 0xa1, 0x2c, 0x49, 0x36,
	0x98, 0x46, 0xeb, 0x28, 0x9b, 0x5e, 0x21, 0xa0, 0xb3, 0x6c, 0x50, 0xec, 0x61, 0xd9, 0x07, 0x15,
	0x5a, 0xa7, 0x49, 0x3a, 0x6d, 0xa8, 0xd4, 0x9c, 0xfe, 0xf9, 0x74, 0x11, 0xe4, 0x69, 0x70, 0x39,
	0x8b, 0x0c, 0xe6, 0xfd, 0x8d, 0x35, 0x5d, 0xab, 0xf0, 0x9b, 0xff, 0xfb, 0x3c, 0x0e, 0xbc, 0xf0,
	0x38, 0x67, 0xb1, 0x83, 0xc4, 0xa2, 0xea, 0x5a, 0xed, 0x5e, 0xa5, 0xb4, 0xd6, 0x28, 0xed, 0x37,
	0xd2, 0x51, 0x18, 0xff, 0xb9, 0xe3, 0xa0, 0x1e, 0x13, 0xff, 0xd2, 0xe1, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x43, 0xf5, 0xcb, 0x0d, 0xea, 0x00, 0x00, 0x00,
}
