// Code generated by protoc-gen-go. DO NOT EDIT.
// source: networkfirewallprofile.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Direction
type NetworkFirewallProfile_Direction int32

const (
	NetworkFirewallProfile_INGRESS NetworkFirewallProfile_Direction = 0
	NetworkFirewallProfile_EGRESS  NetworkFirewallProfile_Direction = 1
)

var NetworkFirewallProfile_Direction_name = map[int32]string{
	0: "INGRESS",
	1: "EGRESS",
}

var NetworkFirewallProfile_Direction_value = map[string]int32{
	"INGRESS": 0,
	"EGRESS":  1,
}

func (x NetworkFirewallProfile_Direction) String() string {
	return proto.EnumName(NetworkFirewallProfile_Direction_name, int32(x))
}

func (NetworkFirewallProfile_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0cfbd3b6098be64, []int{0, 0}
}

type NetworkFirewallProfile_FirewallRule_Proto int32

const (
	NetworkFirewallProfile_FirewallRule_NONE NetworkFirewallProfile_FirewallRule_Proto = 0
	NetworkFirewallProfile_FirewallRule_TCP  NetworkFirewallProfile_FirewallRule_Proto = 1
	NetworkFirewallProfile_FirewallRule_UDP  NetworkFirewallProfile_FirewallRule_Proto = 2
	NetworkFirewallProfile_FirewallRule_ICMP NetworkFirewallProfile_FirewallRule_Proto = 3
)

var NetworkFirewallProfile_FirewallRule_Proto_name = map[int32]string{
	0: "NONE",
	1: "TCP",
	2: "UDP",
	3: "ICMP",
}

var NetworkFirewallProfile_FirewallRule_Proto_value = map[string]int32{
	"NONE": 0,
	"TCP":  1,
	"UDP":  2,
	"ICMP": 3,
}

func (x NetworkFirewallProfile_FirewallRule_Proto) String() string {
	return proto.EnumName(NetworkFirewallProfile_FirewallRule_Proto_name, int32(x))
}

func (NetworkFirewallProfile_FirewallRule_Proto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0cfbd3b6098be64, []int{0, 0, 0}
}

type NetworkFirewallProfile_FirewallRule_Action int32

const (
	NetworkFirewallProfile_FirewallRule_PERMIT         NetworkFirewallProfile_FirewallRule_Action = 0
	NetworkFirewallProfile_FirewallRule_PERMIT_REFLECT NetworkFirewallProfile_FirewallRule_Action = 1
	NetworkFirewallProfile_FirewallRule_DENY           NetworkFirewallProfile_FirewallRule_Action = 2
)

var NetworkFirewallProfile_FirewallRule_Action_name = map[int32]string{
	0: "PERMIT",
	1: "PERMIT_REFLECT",
	2: "DENY",
}

var NetworkFirewallProfile_FirewallRule_Action_value = map[string]int32{
	"PERMIT":         0,
	"PERMIT_REFLECT": 1,
	"DENY":           2,
}

func (x NetworkFirewallProfile_FirewallRule_Action) String() string {
	return proto.EnumName(NetworkFirewallProfile_FirewallRule_Action_name, int32(x))
}

func (NetworkFirewallProfile_FirewallRule_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0cfbd3b6098be64, []int{0, 0, 1}
}

// NetworkFirewallProfile is used to define network firewall profile.
type NetworkFirewallProfile struct {
	// Profile Name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Sase Service Instance Name
	ServiceInstanceName string                           `protobuf:"bytes,2,opt,name=service_instance_name,json=serviceInstanceName,proto3" json:"service_instance_name,omitempty"`
	Direction           NetworkFirewallProfile_Direction `protobuf:"varint,3,opt,name=direction,proto3,enum=model.NetworkFirewallProfile_Direction" json:"direction,omitempty"`
	// Interface
	InterfaceName string `protobuf:"bytes,4,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// List of Network Firewall Rules
	Rules                []*NetworkFirewallProfile_FirewallRule `protobuf:"bytes,5,rep,name=Rules,json=rules,proto3" json:"Rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *NetworkFirewallProfile) Reset()         { *m = NetworkFirewallProfile{} }
func (m *NetworkFirewallProfile) String() string { return proto.CompactTextString(m) }
func (*NetworkFirewallProfile) ProtoMessage()    {}
func (*NetworkFirewallProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cfbd3b6098be64, []int{0}
}

func (m *NetworkFirewallProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkFirewallProfile.Unmarshal(m, b)
}
func (m *NetworkFirewallProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkFirewallProfile.Marshal(b, m, deterministic)
}
func (m *NetworkFirewallProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkFirewallProfile.Merge(m, src)
}
func (m *NetworkFirewallProfile) XXX_Size() int {
	return xxx_messageInfo_NetworkFirewallProfile.Size(m)
}
func (m *NetworkFirewallProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkFirewallProfile.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkFirewallProfile proto.InternalMessageInfo

func (m *NetworkFirewallProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkFirewallProfile) GetServiceInstanceName() string {
	if m != nil {
		return m.ServiceInstanceName
	}
	return ""
}

func (m *NetworkFirewallProfile) GetDirection() NetworkFirewallProfile_Direction {
	if m != nil {
		return m.Direction
	}
	return NetworkFirewallProfile_INGRESS
}

func (m *NetworkFirewallProfile) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *NetworkFirewallProfile) GetRules() []*NetworkFirewallProfile_FirewallRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

// Firewall Rule
type NetworkFirewallProfile_FirewallRule struct {
	Name                 string                                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol             NetworkFirewallProfile_FirewallRule_Proto  `protobuf:"varint,2,opt,name=protocol,proto3,enum=model.NetworkFirewallProfile_FirewallRule_Proto" json:"protocol,omitempty"`
	SrcProtoPort         uint32                                     `protobuf:"varint,3,opt,name=src_proto_port,json=srcProtoPort,proto3" json:"src_proto_port,omitempty"`
	DstProtoPort         uint32                                     `protobuf:"varint,4,opt,name=dst_proto_port,json=dstProtoPort,proto3" json:"dst_proto_port,omitempty"`
	SourceCidr           string                                     `protobuf:"bytes,5,opt,name=source_cidr,json=sourceCidr,proto3" json:"source_cidr,omitempty"`
	DestinationCidr      string                                     `protobuf:"bytes,6,opt,name=destination_cidr,json=destinationCidr,proto3" json:"destination_cidr,omitempty"`
	Action               NetworkFirewallProfile_FirewallRule_Action `protobuf:"varint,7,opt,name=action,proto3,enum=model.NetworkFirewallProfile_FirewallRule_Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *NetworkFirewallProfile_FirewallRule) Reset()         { *m = NetworkFirewallProfile_FirewallRule{} }
func (m *NetworkFirewallProfile_FirewallRule) String() string { return proto.CompactTextString(m) }
func (*NetworkFirewallProfile_FirewallRule) ProtoMessage()    {}
func (*NetworkFirewallProfile_FirewallRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cfbd3b6098be64, []int{0, 0}
}

func (m *NetworkFirewallProfile_FirewallRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkFirewallProfile_FirewallRule.Unmarshal(m, b)
}
func (m *NetworkFirewallProfile_FirewallRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkFirewallProfile_FirewallRule.Marshal(b, m, deterministic)
}
func (m *NetworkFirewallProfile_FirewallRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkFirewallProfile_FirewallRule.Merge(m, src)
}
func (m *NetworkFirewallProfile_FirewallRule) XXX_Size() int {
	return xxx_messageInfo_NetworkFirewallProfile_FirewallRule.Size(m)
}
func (m *NetworkFirewallProfile_FirewallRule) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkFirewallProfile_FirewallRule.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkFirewallProfile_FirewallRule proto.InternalMessageInfo

func (m *NetworkFirewallProfile_FirewallRule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkFirewallProfile_FirewallRule) GetProtocol() NetworkFirewallProfile_FirewallRule_Proto {
	if m != nil {
		return m.Protocol
	}
	return NetworkFirewallProfile_FirewallRule_NONE
}

func (m *NetworkFirewallProfile_FirewallRule) GetSrcProtoPort() uint32 {
	if m != nil {
		return m.SrcProtoPort
	}
	return 0
}

func (m *NetworkFirewallProfile_FirewallRule) GetDstProtoPort() uint32 {
	if m != nil {
		return m.DstProtoPort
	}
	return 0
}

func (m *NetworkFirewallProfile_FirewallRule) GetSourceCidr() string {
	if m != nil {
		return m.SourceCidr
	}
	return ""
}

func (m *NetworkFirewallProfile_FirewallRule) GetDestinationCidr() string {
	if m != nil {
		return m.DestinationCidr
	}
	return ""
}

func (m *NetworkFirewallProfile_FirewallRule) GetAction() NetworkFirewallProfile_FirewallRule_Action {
	if m != nil {
		return m.Action
	}
	return NetworkFirewallProfile_FirewallRule_PERMIT
}

func init() {
	proto.RegisterEnum("model.NetworkFirewallProfile_Direction", NetworkFirewallProfile_Direction_name, NetworkFirewallProfile_Direction_value)
	proto.RegisterEnum("model.NetworkFirewallProfile_FirewallRule_Proto", NetworkFirewallProfile_FirewallRule_Proto_name, NetworkFirewallProfile_FirewallRule_Proto_value)
	proto.RegisterEnum("model.NetworkFirewallProfile_FirewallRule_Action", NetworkFirewallProfile_FirewallRule_Action_name, NetworkFirewallProfile_FirewallRule_Action_value)
	proto.RegisterType((*NetworkFirewallProfile)(nil), "model.NetworkFirewallProfile")
	proto.RegisterType((*NetworkFirewallProfile_FirewallRule)(nil), "model.NetworkFirewallProfile.FirewallRule")
}

func init() {
	proto.RegisterFile("networkfirewallprofile.proto", fileDescriptor_e0cfbd3b6098be64)
}

var fileDescriptor_e0cfbd3b6098be64 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xe1, 0x6e, 0xd3, 0x30,
	0x10, 0xc7, 0x9b, 0xa6, 0x49, 0xd7, 0xeb, 0x16, 0x2c, 0x23, 0x50, 0x85, 0x90, 0xa8, 0xaa, 0x21,
	0x0a, 0x12, 0x11, 0x84, 0x17, 0x00, 0xb5, 0x19, 0x8a, 0xb4, 0x85, 0xc8, 0x2b, 0x1f, 0xf8, 0x14,
	0x85, 0xc4, 0x95, 0x2c, 0xb2, 0xb8, 0xb2, 0x3d, 0xf6, 0x66, 0xbc, 0x16, 0xaf, 0x80, 0x7c, 0x4e,
	0xbb, 0x7e, 0x98, 0x10, 0x7c, 0x3b, 0xdf, 0xfd, 0xfe, 0xf7, 0xf7, 0x9d, 0x0d, 0xcf, 0x3b, 0x6e,
	0xee, 0xa4, 0xfa, 0xb1, 0x15, 0x8a, 0xdf, 0x55, 0x6d, 0xbb, 0x53, 0x72, 0x2b, 0x5a, 0x1e, 0xef,
	0x94, 0x34, 0x92, 0x06, 0x37, 0xb2, 0xe1, 0xed, 0xe2, 0x77, 0x00, 0x4f, 0x73, 0xc7, 0x5d, 0xf4,
	0x5c, 0xe1, 0x38, 0x4a, 0x61, 0xd4, 0x55, 0x37, 0x7c, 0xe6, 0xcd, 0xbd, 0xe5, 0x84, 0x61, 0x4c,
	0x13, 0x78, 0xa2, 0xb9, 0xfa, 0x29, 0x6a, 0x5e, 0x8a, 0x4e, 0x9b, 0xaa, 0xab, 0x79, 0x89, 0xd0,
	0x10, 0xa1, 0xc7, 0x7d, 0x31, 0xeb, 0x6b, 0xb9, 0xd5, 0xa4, 0x30, 0x69, 0x84, 0xe2, 0xb5, 0x11,
	0xb2, 0x9b, 0xf9, 0x73, 0x6f, 0x19, 0x25, 0xaf, 0x62, 0x74, 0x8f, 0x1f, 0x76, 0x8e, 0xd7, 0x7b,
	0x9c, 0xdd, 0x2b, 0xe9, 0x4b, 0x88, 0x44, 0x67, 0xb8, 0xda, 0x56, 0x7b, 0xcf, 0x11, 0x7a, 0x9e,
	0x1d, 0xb2, 0xe8, 0xf6, 0x11, 0x02, 0x76, 0xdb, 0x72, 0x3d, 0x0b, 0xe6, 0xfe, 0x72, 0x9a, 0xbc,
	0xf9, 0xbb, 0xd3, 0xfe, 0x6c, 0x25, 0x2c, 0x50, 0x56, 0xf8, 0xec, 0x97, 0x0f, 0xa7, 0xc7, 0xf9,
	0x07, 0x17, 0x71, 0x09, 0x27, 0xb8, 0xc7, 0x5a, 0xb6, 0x38, 0x7b, 0x94, 0xbc, 0xfb, 0x77, 0xa7,
	0xb8, 0xb0, 0x52, 0x76, 0xe8, 0x40, 0xcf, 0x21, 0xd2, 0xaa, 0x2e, 0xf1, 0x5c, 0xee, 0xa4, 0x32,
	0xb8, 0xa7, 0x33, 0x76, 0xaa, 0x55, 0x8d, 0x6c, 0x21, 0x95, 0xb1, 0x54, 0xa3, 0xcd, 0x31, 0x35,
	0x72, 0x54, 0xa3, 0xcd, 0x3d, 0xf5, 0x02, 0xa6, 0x5a, 0xde, 0xaa, 0x9a, 0x97, 0xb5, 0x68, 0xd4,
	0x2c, 0xc0, 0x4b, 0x83, 0x4b, 0xad, 0x44, 0xa3, 0xe8, 0x6b, 0x20, 0x0d, 0xd7, 0x46, 0x74, 0x95,
	0xdd, 0xab, 0xa3, 0x42, 0xa4, 0x1e, 0x1d, 0xe5, 0x11, 0xcd, 0x20, 0xac, 0xdc, 0xbb, 0x8d, 0x71,
	0xc6, 0xf7, 0xff, 0x31, 0xe3, 0x27, 0xf7, 0x82, 0x7d, 0x83, 0xc5, 0x5b, 0x08, 0xf0, 0x8e, 0xf4,
	0x04, 0x46, 0xf9, 0x97, 0x3c, 0x25, 0x03, 0x3a, 0x06, 0x7f, 0xb3, 0x2a, 0x88, 0x67, 0x83, 0xaf,
	0xeb, 0x82, 0x0c, 0x6d, 0x2d, 0x5b, 0x5d, 0x15, 0xc4, 0x5f, 0x24, 0x10, 0xba, 0x06, 0x14, 0x20,
	0x2c, 0x52, 0x76, 0x95, 0x6d, 0xc8, 0x80, 0x52, 0x88, 0x5c, 0x5c, 0xb2, 0xf4, 0xe2, 0x32, 0x5d,
	0x6d, 0x88, 0x67, 0x35, 0xeb, 0x34, 0xff, 0x46, 0x86, 0x8b, 0x73, 0x98, 0x1c, 0x7e, 0x0e, 0x9d,
	0xc2, 0x38, 0xcb, 0x3f, 0xb3, 0xf4, 0xfa, 0x9a, 0x0c, 0x6c, 0x8f, 0xd4, 0xc5, 0xde, 0xf7, 0x10,
	0xf7, 0xf7, 0xe1, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x13, 0x6e, 0x09, 0x1f, 0x03, 0x00,
	0x00,
}
