// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: saseconfig.proto

package model

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Sase Rule Direction
type SaseConfig_Direction int32

const (
	SaseConfig_Ingress SaseConfig_Direction = 0
	SaseConfig_Egress  SaseConfig_Direction = 1
)

var SaseConfig_Direction_name = map[int32]string{
	0: "Ingress",
	1: "Egress",
}

var SaseConfig_Direction_value = map[string]int32{
	"Ingress": 0,
	"Egress":  1,
}

func (x SaseConfig_Direction) String() string {
	return proto.EnumName(SaseConfig_Direction_name, int32(x))
}

func (SaseConfig_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f523e7d7f9b860d, []int{0, 0}
}

// Sase Rule action
type SaseConfig_Action int32

const (
	SaseConfig_DENY    SaseConfig_Action = 0
	SaseConfig_PERMIT  SaseConfig_Action = 1
	SaseConfig_NAT     SaseConfig_Action = 2
	SaseConfig_FORWARD SaseConfig_Action = 3
	SaseConfig_SECURE  SaseConfig_Action = 4
)

var SaseConfig_Action_name = map[int32]string{
	0: "DENY",
	1: "PERMIT",
	2: "NAT",
	3: "FORWARD",
	4: "SECURE",
}

var SaseConfig_Action_value = map[string]int32{
	"DENY":    0,
	"PERMIT":  1,
	"NAT":     2,
	"FORWARD": 3,
	"SECURE":  4,
}

func (x SaseConfig_Action) String() string {
	return proto.EnumName(SaseConfig_Action_name, int32(x))
}

func (SaseConfig_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f523e7d7f9b860d, []int{0, 1}
}

// Protocol
type SaseConfig_Match_Proto int32

const (
	SaseConfig_Match_TCP SaseConfig_Match_Proto = 0
	SaseConfig_Match_UDP SaseConfig_Match_Proto = 1
)

var SaseConfig_Match_Proto_name = map[int32]string{
	0: "TCP",
	1: "UDP",
}

var SaseConfig_Match_Proto_value = map[string]int32{
	"TCP": 0,
	"UDP": 1,
}

func (x SaseConfig_Match_Proto) String() string {
	return proto.EnumName(SaseConfig_Match_Proto_name, int32(x))
}

func (SaseConfig_Match_Proto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f523e7d7f9b860d, []int{0, 0, 0}
}

// SaseConfig is used to store definition of a sase config as a k8s CRD resource.
type SaseConfig struct {
	// Name of the SaseConfig
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Sase Service Name
	SaseServiceName string `protobuf:"bytes,2,opt,name=sase_service_name,json=saseServiceName,proto3" json:"sase_service_name,omitempty"`
	// Sase Rule Direction
	Direction SaseConfig_Direction `protobuf:"varint,3,opt,name=direction,proto3,enum=model.SaseConfig_Direction" json:"direction,omitempty"`
	// Sase Rule Match condition
	Match *SaseConfig_Match `protobuf:"bytes,4,opt,name=match,proto3" json:"match,omitempty"`
	// Sase Rule action
	Action               SaseConfig_Action `protobuf:"varint,5,opt,name=action,proto3,enum=model.SaseConfig_Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SaseConfig) Reset()         { *m = SaseConfig{} }
func (m *SaseConfig) String() string { return proto.CompactTextString(m) }
func (*SaseConfig) ProtoMessage()    {}
func (*SaseConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f523e7d7f9b860d, []int{0}
}
func (m *SaseConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaseConfig.Unmarshal(m, b)
}
func (m *SaseConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaseConfig.Marshal(b, m, deterministic)
}
func (m *SaseConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaseConfig.Merge(m, src)
}
func (m *SaseConfig) XXX_Size() int {
	return xxx_messageInfo_SaseConfig.Size(m)
}
func (m *SaseConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SaseConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SaseConfig proto.InternalMessageInfo

func (m *SaseConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SaseConfig) GetSaseServiceName() string {
	if m != nil {
		return m.SaseServiceName
	}
	return ""
}

func (m *SaseConfig) GetDirection() SaseConfig_Direction {
	if m != nil {
		return m.Direction
	}
	return SaseConfig_Ingress
}

func (m *SaseConfig) GetMatch() *SaseConfig_Match {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *SaseConfig) GetAction() SaseConfig_Action {
	if m != nil {
		return m.Action
	}
	return SaseConfig_DENY
}

// Sase Rule Match Attribute. 5 tuple match fields
type SaseConfig_Match struct {
	// interface name
	InterfaceName string `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// ip address to statically assign to the interface
	Ip    string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Proto SaseConfig_Match_Proto `protobuf:"varint,3,opt,name=proto,proto3,enum=model.SaseConfig_Match_Proto" json:"proto,omitempty"`
	// Application Port
	Port                 string   `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaseConfig_Match) Reset()         { *m = SaseConfig_Match{} }
func (m *SaseConfig_Match) String() string { return proto.CompactTextString(m) }
func (*SaseConfig_Match) ProtoMessage()    {}
func (*SaseConfig_Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f523e7d7f9b860d, []int{0, 0}
}
func (m *SaseConfig_Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaseConfig_Match.Unmarshal(m, b)
}
func (m *SaseConfig_Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaseConfig_Match.Marshal(b, m, deterministic)
}
func (m *SaseConfig_Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaseConfig_Match.Merge(m, src)
}
func (m *SaseConfig_Match) XXX_Size() int {
	return xxx_messageInfo_SaseConfig_Match.Size(m)
}
func (m *SaseConfig_Match) XXX_DiscardUnknown() {
	xxx_messageInfo_SaseConfig_Match.DiscardUnknown(m)
}

var xxx_messageInfo_SaseConfig_Match proto.InternalMessageInfo

func (m *SaseConfig_Match) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *SaseConfig_Match) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *SaseConfig_Match) GetProto() SaseConfig_Match_Proto {
	if m != nil {
		return m.Proto
	}
	return SaseConfig_Match_TCP
}

func (m *SaseConfig_Match) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func init() {
	proto.RegisterEnum("model.SaseConfig_Direction", SaseConfig_Direction_name, SaseConfig_Direction_value)
	proto.RegisterEnum("model.SaseConfig_Action", SaseConfig_Action_name, SaseConfig_Action_value)
	proto.RegisterEnum("model.SaseConfig_Match_Proto", SaseConfig_Match_Proto_name, SaseConfig_Match_Proto_value)
	proto.RegisterType((*SaseConfig)(nil), "model.SaseConfig")
	proto.RegisterType((*SaseConfig_Match)(nil), "model.SaseConfig.Match")
}

func init() { proto.RegisterFile("saseconfig.proto", fileDescriptor_8f523e7d7f9b860d) }

var fileDescriptor_8f523e7d7f9b860d = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xbb, 0xf9, 0x57, 0x33, 0xc5, 0xba, 0xee, 0xc5, 0xa8, 0x08, 0x25, 0x28, 0x14, 0xc1,
	0x20, 0xed, 0xc9, 0x9b, 0xa5, 0x89, 0xd0, 0x43, 0x6b, 0xd8, 0xb6, 0x88, 0xa7, 0x12, 0xd3, 0x6d,
	0x5d, 0xb0, 0x49, 0x48, 0x82, 0x1f, 0xc8, 0xef, 0xe8, 0x5d, 0x76, 0xb6, 0x7f, 0x0e, 0xc5, 0xdb,
	0x63, 0xdf, 0x6f, 0xe7, 0xcd, 0x1b, 0xa0, 0x55, 0x52, 0x89, 0x34, 0xcf, 0x56, 0x72, 0x1d, 0x14,
	0x65, 0x5e, 0xe7, 0xcc, 0xde, 0xe4, 0x4b, 0xf1, 0xe5, 0xff, 0x9a, 0x00, 0xd3, 0xa4, 0x12, 0x43,
	0xf4, 0x18, 0x03, 0x2b, 0x4b, 0x36, 0xc2, 0x23, 0x1d, 0xd2, 0x75, 0x39, 0x6a, 0x76, 0x0f, 0xe7,
	0xea, 0xf7, 0xa2, 0x12, 0xe5, 0xb7, 0x4c, 0xc5, 0x02, 0x01, 0x03, 0x81, 0x33, 0x65, 0x4c, 0xf5,
	0xfb, 0x44, 0xb1, 0x4f, 0xe0, 0x2e, 0x65, 0x29, 0xd2, 0x5a, 0xe6, 0x99, 0x67, 0x76, 0x48, 0xb7,
	0xdd, 0xbb, 0x0e, 0x30, 0x29, 0x38, 0xa4, 0x04, 0xe1, 0x0e, 0xe1, 0x07, 0x9a, 0x3d, 0x80, 0xbd,
	0x49, 0xea, 0xf4, 0xd3, 0xb3, 0x3a, 0xa4, 0xdb, 0xea, 0x5d, 0x1c, 0x7f, 0x1b, 0x2b, 0x9b, 0x6b,
	0x8a, 0x3d, 0x82, 0x93, 0xe8, 0x18, 0x1b, 0x63, 0xbc, 0x63, 0x7e, 0xa0, 0x33, 0xb6, 0xdc, 0xd5,
	0x0f, 0x01, 0x1b, 0x47, 0xb0, 0x3b, 0x68, 0xcb, 0xac, 0x16, 0xe5, 0x2a, 0xd9, 0xd5, 0xd1, 0x7d,
	0x4f, 0xf7, 0xaf, 0x58, 0xa6, 0x0d, 0x86, 0x2c, 0xb6, 0x4d, 0x0d, 0x59, 0xb0, 0x3e, 0xd8, 0x78,
	0xbb, 0x6d, 0xb1, 0x9b, 0x7f, 0x36, 0x0c, 0x62, 0x05, 0x71, 0xcd, 0xaa, 0x8b, 0x16, 0x79, 0x59,
	0x63, 0x2b, 0x97, 0xa3, 0xf6, 0x2f, 0xc1, 0x46, 0x86, 0x35, 0xc1, 0x9c, 0x0d, 0x63, 0xda, 0x50,
	0x62, 0x1e, 0xc6, 0x94, 0xf8, 0xb7, 0xe0, 0xee, 0xaf, 0xc3, 0x5a, 0xd0, 0x1c, 0x65, 0xeb, 0x52,
	0x54, 0x15, 0x6d, 0x30, 0x00, 0x27, 0xd2, 0x9a, 0xf8, 0xcf, 0xe0, 0xe8, 0x72, 0xec, 0x04, 0xac,
	0x30, 0x9a, 0xbc, 0x6b, 0x3f, 0x8e, 0xf8, 0x78, 0x34, 0xa3, 0x44, 0x8d, 0x9b, 0x0c, 0x66, 0xd4,
	0x50, 0x13, 0x5e, 0x5e, 0xf9, 0xdb, 0x80, 0x87, 0xd4, 0x54, 0xc4, 0x34, 0x1a, 0xce, 0x79, 0x44,
	0xad, 0x0f, 0x07, 0xb7, 0xeb, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x88, 0xb8, 0x88, 0x19,
	0x02, 0x00, 0x00,
}
