// Code generated by protoc-gen-go. DO NOT EDIT.
// source: saseserviceinterface.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SaseServiceInterface is used to store definition of a sase config as a k8s CRD resource.
type SaseServiceInterface struct {
	// InterfaceName
	InterfaceName string `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// InterfaceType
	InterfaceType string `protobuf:"bytes,2,opt,name=interface_type,json=interfaceType,proto3" json:"interface_type,omitempty"`
	// Sase Service Instance Name
	ServiceInstanceName string `protobuf:"bytes,3,opt,name=service_instance_name,json=serviceInstanceName,proto3" json:"service_instance_name,omitempty"`
	// Interface Mode
	InterfaceMode string `protobuf:"bytes,4,opt,name=interface_mode,json=interfaceMode,proto3" json:"interface_mode,omitempty"`
	// Interface L3 Address
	InterfaceL3Address string `protobuf:"bytes,5,opt,name=interface_l3_address,json=interfaceL3Address,proto3" json:"interface_l3_address,omitempty"`
	// Interface Parent
	InterfaceParent      string   `protobuf:"bytes,6,opt,name=interface_parent,json=interfaceParent,proto3" json:"interface_parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaseServiceInterface) Reset()         { *m = SaseServiceInterface{} }
func (m *SaseServiceInterface) String() string { return proto.CompactTextString(m) }
func (*SaseServiceInterface) ProtoMessage()    {}
func (*SaseServiceInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfcb8b1233648d9e, []int{0}
}

func (m *SaseServiceInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaseServiceInterface.Unmarshal(m, b)
}
func (m *SaseServiceInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaseServiceInterface.Marshal(b, m, deterministic)
}
func (m *SaseServiceInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaseServiceInterface.Merge(m, src)
}
func (m *SaseServiceInterface) XXX_Size() int {
	return xxx_messageInfo_SaseServiceInterface.Size(m)
}
func (m *SaseServiceInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_SaseServiceInterface.DiscardUnknown(m)
}

var xxx_messageInfo_SaseServiceInterface proto.InternalMessageInfo

func (m *SaseServiceInterface) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *SaseServiceInterface) GetInterfaceType() string {
	if m != nil {
		return m.InterfaceType
	}
	return ""
}

func (m *SaseServiceInterface) GetServiceInstanceName() string {
	if m != nil {
		return m.ServiceInstanceName
	}
	return ""
}

func (m *SaseServiceInterface) GetInterfaceMode() string {
	if m != nil {
		return m.InterfaceMode
	}
	return ""
}

func (m *SaseServiceInterface) GetInterfaceL3Address() string {
	if m != nil {
		return m.InterfaceL3Address
	}
	return ""
}

func (m *SaseServiceInterface) GetInterfaceParent() string {
	if m != nil {
		return m.InterfaceParent
	}
	return ""
}

func init() {
	proto.RegisterType((*SaseServiceInterface)(nil), "model.SaseServiceInterface")
}

func init() {
	proto.RegisterFile("saseserviceinterface.proto", fileDescriptor_cfcb8b1233648d9e)
}

var fileDescriptor_cfcb8b1233648d9e = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x4e, 0x2c, 0x4e,
	0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xcd, 0xcc, 0x2b, 0x49, 0x2d, 0x4a, 0x4b, 0x4c, 0x4e,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x9a, 0xc3,
	0xc4, 0x25, 0x12, 0x9c, 0x58, 0x9c, 0x1a, 0x0c, 0x51, 0xe5, 0x09, 0x53, 0x25, 0xa4, 0xca, 0xc5,
	0x07, 0xd7, 0x12, 0x9f, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x0b,
	0x17, 0xf5, 0x4b, 0xcc, 0x45, 0x53, 0x56, 0x52, 0x59, 0x90, 0x2a, 0xc1, 0x84, 0xa6, 0x2c, 0xa4,
	0xb2, 0x20, 0x55, 0xc8, 0x88, 0x4b, 0x14, 0xea, 0x8e, 0xf8, 0xcc, 0xbc, 0xe2, 0x92, 0xc4, 0x3c,
	0x98, 0xa1, 0xcc, 0x60, 0xd5, 0xc2, 0xc5, 0x30, 0xeb, 0x21, 0x72, 0x98, 0x46, 0x83, 0x5c, 0x2b,
	0xc1, 0x82, 0x66, 0xb4, 0x6f, 0x7e, 0x4a, 0xaa, 0x90, 0x01, 0x97, 0x08, 0x42, 0x59, 0x8e, 0x71,
	0x7c, 0x62, 0x4a, 0x4a, 0x51, 0x6a, 0x71, 0xb1, 0x04, 0x2b, 0x58, 0xb1, 0x10, 0x5c, 0xce, 0xc7,
	0xd8, 0x11, 0x22, 0x23, 0xa4, 0xc9, 0x25, 0x80, 0xd0, 0x51, 0x90, 0x58, 0x94, 0x9a, 0x57, 0x22,
	0xc1, 0x06, 0x56, 0xcd, 0x0f, 0x17, 0x0f, 0x00, 0x0b, 0x27, 0xb1, 0x81, 0x03, 0xcb, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x69, 0xde, 0x12, 0x37, 0x4a, 0x01, 0x00, 0x00,
}
