// Code generated by protoc-gen-go. DO NOT EDIT.
// source: securityassociations.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SecurityAssociation is used to store definition for security association as a k8s CRD resource.
type SecurityAssociation struct {
	// Security Association Name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Sase Service Instance Name
	ServiceInstanceName string `protobuf:"bytes,2,opt,name=service_instance_name,json=serviceInstanceName,proto3" json:"service_instance_name,omitempty"`
	// Authentication algorithm
	AuthAlgorithm string `protobuf:"bytes,3,opt,name=auth_algorithm,json=authAlgorithm,proto3" json:"auth_algorithm,omitempty"`
	// Authentication Shared Secret key
	AuthSharedKey string `protobuf:"bytes,4,opt,name=auth_shared_key,json=authSharedKey,proto3" json:"auth_shared_key,omitempty"`
	// Encryption Algorithm
	EncryptAlgorithm string `protobuf:"bytes,5,opt,name=encrypt_algorithm,json=encryptAlgorithm,proto3" json:"encrypt_algorithm,omitempty"`
	// Encryption Shared Key
	EncryptSharedKey string `protobuf:"bytes,6,opt,name=encrypt_shared_key,json=encryptSharedKey,proto3" json:"encrypt_shared_key,omitempty"`
	// Inbound SA Index
	SaInboundId uint32 `protobuf:"varint,7,opt,name=sa_inbound_id,json=saInboundId,proto3" json:"sa_inbound_id,omitempty"`
	// Outbound SA Index
	SaOutboundId uint32 `protobuf:"varint,8,opt,name=sa_outbound_id,json=saOutboundId,proto3" json:"sa_outbound_id,omitempty"`
	// Mode Tunnel or Transport Mode
	Mode                 string   `protobuf:"bytes,9,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityAssociation) Reset()         { *m = SecurityAssociation{} }
func (m *SecurityAssociation) String() string { return proto.CompactTextString(m) }
func (*SecurityAssociation) ProtoMessage()    {}
func (*SecurityAssociation) Descriptor() ([]byte, []int) {
	return fileDescriptor_711ea7d1781d1e8b, []int{0}
}

func (m *SecurityAssociation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityAssociation.Unmarshal(m, b)
}
func (m *SecurityAssociation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityAssociation.Marshal(b, m, deterministic)
}
func (m *SecurityAssociation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityAssociation.Merge(m, src)
}
func (m *SecurityAssociation) XXX_Size() int {
	return xxx_messageInfo_SecurityAssociation.Size(m)
}
func (m *SecurityAssociation) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityAssociation.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityAssociation proto.InternalMessageInfo

func (m *SecurityAssociation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SecurityAssociation) GetServiceInstanceName() string {
	if m != nil {
		return m.ServiceInstanceName
	}
	return ""
}

func (m *SecurityAssociation) GetAuthAlgorithm() string {
	if m != nil {
		return m.AuthAlgorithm
	}
	return ""
}

func (m *SecurityAssociation) GetAuthSharedKey() string {
	if m != nil {
		return m.AuthSharedKey
	}
	return ""
}

func (m *SecurityAssociation) GetEncryptAlgorithm() string {
	if m != nil {
		return m.EncryptAlgorithm
	}
	return ""
}

func (m *SecurityAssociation) GetEncryptSharedKey() string {
	if m != nil {
		return m.EncryptSharedKey
	}
	return ""
}

func (m *SecurityAssociation) GetSaInboundId() uint32 {
	if m != nil {
		return m.SaInboundId
	}
	return 0
}

func (m *SecurityAssociation) GetSaOutboundId() uint32 {
	if m != nil {
		return m.SaOutboundId
	}
	return 0
}

func (m *SecurityAssociation) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func init() {
	proto.RegisterType((*SecurityAssociation)(nil), "model.SecurityAssociation")
}

func init() {
	proto.RegisterFile("securityassociations.proto", fileDescriptor_711ea7d1781d1e8b)
}

var fileDescriptor_711ea7d1781d1e8b = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x06, 0x60, 0x5a, 0xdb, 0x6a, 0x47, 0xb7, 0x6a, 0x8a, 0xb0, 0x78, 0x2a, 0x45, 0xa5, 0xa0,
	0x78, 0xd0, 0x27, 0xe8, 0x71, 0x11, 0x14, 0xda, 0x07, 0x08, 0xd3, 0xcd, 0xe0, 0x06, 0xbb, 0x49,
	0xc9, 0x64, 0x85, 0x7d, 0x60, 0xdf, 0x43, 0x92, 0xa6, 0x6e, 0xbd, 0x85, 0x7f, 0xbe, 0xfc, 0x87,
	0x1f, 0x6e, 0x99, 0xca, 0xc6, 0x69, 0xdf, 0x22, 0xb3, 0x2d, 0x35, 0x7a, 0x6d, 0x0d, 0x3f, 0xef,
	0x9c, 0xf5, 0x56, 0x0c, 0x6b, 0xab, 0x68, 0x3b, 0xff, 0xe9, 0xc3, 0x74, 0x9d, 0xd4, 0xb2, 0x53,
	0x42, 0xc0, 0xc0, 0x60, 0x4d, 0x79, 0x6f, 0xd6, 0x5b, 0x8c, 0x57, 0xf1, 0x2d, 0x5e, 0xe0, 0x86,
	0xc9, 0x7d, 0xeb, 0x92, 0xa4, 0x36, 0xec, 0xd1, 0x94, 0x24, 0x23, 0xea, 0x47, 0x34, 0x4d, 0xc7,
	0x22, 0xdd, 0xde, 0xc3, 0x9f, 0x7b, 0x98, 0x60, 0xe3, 0x2b, 0x89, 0xdb, 0x4f, 0xeb, 0xb4, 0xaf,
	0xea, 0xfc, 0x24, 0xe2, 0x2c, 0xa4, 0xcb, 0x43, 0x28, 0x1e, 0xe0, 0x32, 0x32, 0xae, 0xd0, 0x91,
	0x92, 0x5f, 0xd4, 0xe6, 0x83, 0xce, 0xad, 0x63, 0xfa, 0x46, 0xad, 0x78, 0x84, 0x6b, 0x32, 0xa5,
	0x6b, 0x77, 0xfe, 0xa8, 0x71, 0x18, 0xe5, 0x55, 0x3a, 0x74, 0xa5, 0x4f, 0x20, 0x0e, 0xf8, 0xa8,
	0x77, 0xf4, 0x4f, 0x77, 0xd5, 0x73, 0xc8, 0x18, 0xa5, 0x36, 0x1b, 0xdb, 0x18, 0x25, 0xb5, 0xca,
	0x4f, 0x67, 0xbd, 0x45, 0xb6, 0x3a, 0x67, 0x2c, 0xf6, 0x59, 0xa1, 0xc4, 0x1d, 0x4c, 0x18, 0xa5,
	0x6d, 0xfc, 0x1f, 0x3a, 0x8b, 0xe8, 0x82, 0xf1, 0x23, 0x85, 0x85, 0x0a, 0xdb, 0x85, 0x71, 0xf3,
	0xf1, 0x7e, 0xbb, 0xf0, 0xde, 0x8c, 0xe2, 0xea, 0xaf, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d,
	0x16, 0x1a, 0x1b, 0x93, 0x01, 0x00, 0x00,
}
