// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: serviceroute.proto

package model

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// ServiceRoute is used to store definition for a Sase Service Route
type ServiceRoute struct {
	// Sase Service Instance Name
	ServiceInstanceName string `protobuf:"bytes,1,opt,name=service_instance_name,json=serviceInstanceName,proto3" json:"service_instance_name,omitempty"`
	// Destination Network
	DestinationNetwork string `protobuf:"bytes,2,opt,name=destination_network,json=destinationNetwork,proto3" json:"destination_network,omitempty"`
	// Gateway IP Address
	GatewayAddress string `protobuf:"bytes,3,opt,name=gateway_address,json=gatewayAddress,proto3" json:"gateway_address,omitempty"`
	// Gateway service ID
	GatewayServiceId string `protobuf:"bytes,4,opt,name=gateway_service_id,json=gatewayServiceId,proto3" json:"gateway_service_id,omitempty"`
	// Gateway network. Identifies VRF
	GatewayNetwork string `protobuf:"bytes,5,opt,name=gateway_network,json=gatewayNetwork,proto3" json:"gateway_network,omitempty"`
	// egress interface
	EgressInterface      string   `protobuf:"bytes,6,opt,name=egress_interface,json=egressInterface,proto3" json:"egress_interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceRoute) Reset()         { *m = ServiceRoute{} }
func (m *ServiceRoute) String() string { return proto.CompactTextString(m) }
func (*ServiceRoute) ProtoMessage()    {}
func (*ServiceRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4d8730375bccbc6, []int{0}
}
func (m *ServiceRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRoute.Unmarshal(m, b)
}
func (m *ServiceRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRoute.Marshal(b, m, deterministic)
}
func (m *ServiceRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRoute.Merge(m, src)
}
func (m *ServiceRoute) XXX_Size() int {
	return xxx_messageInfo_ServiceRoute.Size(m)
}
func (m *ServiceRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRoute.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRoute proto.InternalMessageInfo

func (m *ServiceRoute) GetServiceInstanceName() string {
	if m != nil {
		return m.ServiceInstanceName
	}
	return ""
}

func (m *ServiceRoute) GetDestinationNetwork() string {
	if m != nil {
		return m.DestinationNetwork
	}
	return ""
}

func (m *ServiceRoute) GetGatewayAddress() string {
	if m != nil {
		return m.GatewayAddress
	}
	return ""
}

func (m *ServiceRoute) GetGatewayServiceId() string {
	if m != nil {
		return m.GatewayServiceId
	}
	return ""
}

func (m *ServiceRoute) GetGatewayNetwork() string {
	if m != nil {
		return m.GatewayNetwork
	}
	return ""
}

func (m *ServiceRoute) GetEgressInterface() string {
	if m != nil {
		return m.EgressInterface
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceRoute)(nil), "model.ServiceRoute")
}

func init() { proto.RegisterFile("serviceroute.proto", fileDescriptor_b4d8730375bccbc6) }

var fileDescriptor_b4d8730375bccbc6 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4a, 0xc5, 0x30,
	0x10, 0x85, 0xb9, 0x57, 0x6f, 0xc1, 0x20, 0xb6, 0x4c, 0x11, 0xb2, 0x14, 0x37, 0x2a, 0x88, 0x82,
	0x3e, 0x81, 0xcb, 0x6e, 0xba, 0xa8, 0x0f, 0x10, 0xc6, 0x66, 0x2c, 0x41, 0x9b, 0x48, 0x32, 0x5a,
	0x7c, 0x19, 0x9f, 0x55, 0x9a, 0x1f, 0xa9, 0xdb, 0xf3, 0x7d, 0x99, 0x73, 0x88, 0x80, 0x40, 0xfe,
	0xcb, 0x8c, 0xe4, 0xdd, 0x27, 0xd3, 0xdd, 0x87, 0x77, 0xec, 0xe0, 0x30, 0x3b, 0x4d, 0xef, 0x97,
	0x3f, 0x7b, 0x71, 0xfa, 0x9c, 0xe8, 0xb0, 0x52, 0x78, 0x10, 0xe7, 0xd9, 0x56, 0xc6, 0x06, 0x46,
	0x3b, 0x92, 0xb2, 0x38, 0x93, 0xdc, 0x5d, 0xec, 0xae, 0x4f, 0x86, 0x36, 0xc3, 0x2e, 0xb3, 0x1e,
	0x67, 0x82, 0x7b, 0xd1, 0x6a, 0x0a, 0x6c, 0x2c, 0xb2, 0x71, 0x56, 0x59, 0xe2, 0xc5, 0xf9, 0x37,
	0xb9, 0x8f, 0x2f, 0x60, 0x83, 0xfa, 0x44, 0xe0, 0x4a, 0xd4, 0x13, 0x32, 0x2d, 0xf8, 0xad, 0x50,
	0x6b, 0x4f, 0x21, 0xc8, 0xa3, 0x28, 0x9f, 0xe5, 0xf8, 0x29, 0xa5, 0x70, 0x2b, 0xa0, 0x88, 0x7f,
	0xab, 0xb4, 0x3c, 0x8e, 0x6e, 0x93, 0x49, 0x9e, 0xdf, 0xe9, 0xed, 0xd9, 0xb2, 0xe1, 0xf0, 0xef,
	0x6c, 0xe9, 0xbf, 0x11, 0x0d, 0x4d, 0x6b, 0x81, 0x32, 0x96, 0xc9, 0xbf, 0xe2, 0x48, 0xb2, 0x8a,
	0x66, 0x9d, 0xf2, 0xae, 0xc4, 0x2f, 0x55, 0xfc, 0xae, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x86, 0xcd, 0x8c, 0x6b, 0x44, 0x01, 0x00, 0x00,
}
