// Code generated by protoc-gen-go. DO NOT EDIT.
// source: siteresourcegroup.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SiteResourceGroup is used to store definition of a SiteResourceGroup as a k8s CRD resource.
type SiteResourceGroup struct {
	// Site Name
	SiteName string `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	// List of local networks in the site
	LocalNetwork []*SiteResourceGroup_NetworkInfo `protobuf:"bytes,2,rep,name=local_network,json=localNetwork,proto3" json:"local_network,omitempty"`
	// List of Public IPs in the site
	PublicNetwork        []*SiteResourceGroup_NetworkInfo `protobuf:"bytes,3,rep,name=public_network,json=publicNetwork,proto3" json:"public_network,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *SiteResourceGroup) Reset()         { *m = SiteResourceGroup{} }
func (m *SiteResourceGroup) String() string { return proto.CompactTextString(m) }
func (*SiteResourceGroup) ProtoMessage()    {}
func (*SiteResourceGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd755777b3f2eaa7, []int{0}
}

func (m *SiteResourceGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SiteResourceGroup.Unmarshal(m, b)
}
func (m *SiteResourceGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SiteResourceGroup.Marshal(b, m, deterministic)
}
func (m *SiteResourceGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SiteResourceGroup.Merge(m, src)
}
func (m *SiteResourceGroup) XXX_Size() int {
	return xxx_messageInfo_SiteResourceGroup.Size(m)
}
func (m *SiteResourceGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_SiteResourceGroup.DiscardUnknown(m)
}

var xxx_messageInfo_SiteResourceGroup proto.InternalMessageInfo

func (m *SiteResourceGroup) GetSiteName() string {
	if m != nil {
		return m.SiteName
	}
	return ""
}

func (m *SiteResourceGroup) GetLocalNetwork() []*SiteResourceGroup_NetworkInfo {
	if m != nil {
		return m.LocalNetwork
	}
	return nil
}

func (m *SiteResourceGroup) GetPublicNetwork() []*SiteResourceGroup_NetworkInfo {
	if m != nil {
		return m.PublicNetwork
	}
	return nil
}

// list of physical interfaces on individual nodes
type SiteResourceGroup_NetworkInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NetworkCidr          string   `protobuf:"bytes,2,opt,name=network_cidr,json=networkCidr,proto3" json:"network_cidr,omitempty"`
	NetworkType          string   `protobuf:"bytes,3,opt,name=network_type,json=networkType,proto3" json:"network_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SiteResourceGroup_NetworkInfo) Reset()         { *m = SiteResourceGroup_NetworkInfo{} }
func (m *SiteResourceGroup_NetworkInfo) String() string { return proto.CompactTextString(m) }
func (*SiteResourceGroup_NetworkInfo) ProtoMessage()    {}
func (*SiteResourceGroup_NetworkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd755777b3f2eaa7, []int{0, 0}
}

func (m *SiteResourceGroup_NetworkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SiteResourceGroup_NetworkInfo.Unmarshal(m, b)
}
func (m *SiteResourceGroup_NetworkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SiteResourceGroup_NetworkInfo.Marshal(b, m, deterministic)
}
func (m *SiteResourceGroup_NetworkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SiteResourceGroup_NetworkInfo.Merge(m, src)
}
func (m *SiteResourceGroup_NetworkInfo) XXX_Size() int {
	return xxx_messageInfo_SiteResourceGroup_NetworkInfo.Size(m)
}
func (m *SiteResourceGroup_NetworkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SiteResourceGroup_NetworkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SiteResourceGroup_NetworkInfo proto.InternalMessageInfo

func (m *SiteResourceGroup_NetworkInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SiteResourceGroup_NetworkInfo) GetNetworkCidr() string {
	if m != nil {
		return m.NetworkCidr
	}
	return ""
}

func (m *SiteResourceGroup_NetworkInfo) GetNetworkType() string {
	if m != nil {
		return m.NetworkType
	}
	return ""
}

func init() {
	proto.RegisterType((*SiteResourceGroup)(nil), "model.SiteResourceGroup")
	proto.RegisterType((*SiteResourceGroup_NetworkInfo)(nil), "model.SiteResourceGroup.NetworkInfo")
}

func init() {
	proto.RegisterFile("siteresourcegroup.proto", fileDescriptor_fd755777b3f2eaa7)
}

var fileDescriptor_fd755777b3f2eaa7 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0xce, 0x2c, 0x49,
	0x2d, 0x4a, 0x2d, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0x4d, 0x2f, 0xca, 0x2f, 0x2d, 0xd0, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0xda, 0xc8, 0xc4, 0x25, 0x18,
	0x9c, 0x59, 0x92, 0x1a, 0x04, 0x55, 0xe2, 0x0e, 0x52, 0x22, 0x24, 0xcd, 0xc5, 0x09, 0xd2, 0x17,
	0x9f, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x01, 0x12, 0xf0, 0x4b,
	0xcc, 0x4d, 0x15, 0xf2, 0xe4, 0xe2, 0xcd, 0xc9, 0x4f, 0x4e, 0xcc, 0x89, 0xcf, 0x4b, 0x2d, 0x29,
	0xcf, 0x2f, 0xca, 0x96, 0x60, 0x52, 0x60, 0xd6, 0xe0, 0x36, 0x52, 0xd1, 0x03, 0x9b, 0xa8, 0x87,
	0x61, 0x9a, 0x9e, 0x1f, 0x44, 0x9d, 0x67, 0x5e, 0x5a, 0x7e, 0x10, 0x0f, 0x58, 0x2b, 0x54, 0x44,
	0xc8, 0x9b, 0x8b, 0xaf, 0xa0, 0x34, 0x29, 0x27, 0x33, 0x19, 0x6e, 0x16, 0x33, 0x09, 0x66, 0xf1,
	0x42, 0xf4, 0x42, 0x85, 0xa4, 0xd2, 0xb9, 0xb8, 0x91, 0x64, 0x85, 0x84, 0xb8, 0x58, 0x90, 0x9c,
	0x0f, 0x66, 0x0b, 0x29, 0x72, 0xf1, 0x40, 0x2d, 0x8a, 0x4f, 0xce, 0x4c, 0x29, 0x92, 0x60, 0x02,
	0xcb, 0x71, 0x43, 0xc5, 0x9c, 0x33, 0x53, 0x8a, 0x90, 0x95, 0x94, 0x54, 0x16, 0xa4, 0x4a, 0x30,
	0xa3, 0x28, 0x09, 0xa9, 0x2c, 0x48, 0x4d, 0x62, 0x03, 0x87, 0xa0, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xa0, 0xc0, 0xae, 0x60, 0x5c, 0x01, 0x00, 0x00,
}
