// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1

// CustomConfigurationListerExpansion allows custom methods to be added to
// CustomConfigurationLister.
type CustomConfigurationListerExpansion interface{}

// CustomConfigurationNamespaceListerExpansion allows custom methods to be added to
// CustomConfigurationNamespaceLister.
type CustomConfigurationNamespaceListerExpansion interface{}

// CustomNetworkListerExpansion allows custom methods to be added to
// CustomNetworkLister.
type CustomNetworkListerExpansion interface{}

// CustomNetworkNamespaceListerExpansion allows custom methods to be added to
// CustomNetworkNamespaceLister.
type CustomNetworkNamespaceListerExpansion interface{}

// ExternalInterfaceListerExpansion allows custom methods to be added to
// ExternalInterfaceLister.
type ExternalInterfaceListerExpansion interface{}

// ExternalInterfaceNamespaceListerExpansion allows custom methods to be added to
// ExternalInterfaceNamespaceLister.
type ExternalInterfaceNamespaceListerExpansion interface{}

// IPSecVpnTunnelListerExpansion allows custom methods to be added to
// IPSecVpnTunnelLister.
type IPSecVpnTunnelListerExpansion interface{}

// IPSecVpnTunnelNamespaceListerExpansion allows custom methods to be added to
// IPSecVpnTunnelNamespaceLister.
type IPSecVpnTunnelNamespaceListerExpansion interface{}

// NetworkFirewallProfileListerExpansion allows custom methods to be added to
// NetworkFirewallProfileLister.
type NetworkFirewallProfileListerExpansion interface{}

// NetworkFirewallProfileNamespaceListerExpansion allows custom methods to be added to
// NetworkFirewallProfileNamespaceLister.
type NetworkFirewallProfileNamespaceListerExpansion interface{}

// SaseServiceInterfaceListerExpansion allows custom methods to be added to
// SaseServiceInterfaceLister.
type SaseServiceInterfaceListerExpansion interface{}

// SaseServiceInterfaceNamespaceListerExpansion allows custom methods to be added to
// SaseServiceInterfaceNamespaceLister.
type SaseServiceInterfaceNamespaceListerExpansion interface{}

// SaseServicePolicyListerExpansion allows custom methods to be added to
// SaseServicePolicyLister.
type SaseServicePolicyListerExpansion interface{}

// SaseServicePolicyNamespaceListerExpansion allows custom methods to be added to
// SaseServicePolicyNamespaceLister.
type SaseServicePolicyNamespaceListerExpansion interface{}

// SecurityAssociationListerExpansion allows custom methods to be added to
// SecurityAssociationLister.
type SecurityAssociationListerExpansion interface{}

// SecurityAssociationNamespaceListerExpansion allows custom methods to be added to
// SecurityAssociationNamespaceLister.
type SecurityAssociationNamespaceListerExpansion interface{}

// ServiceFunctionChainListerExpansion allows custom methods to be added to
// ServiceFunctionChainLister.
type ServiceFunctionChainListerExpansion interface{}

// ServiceFunctionChainNamespaceListerExpansion allows custom methods to be added to
// ServiceFunctionChainNamespaceLister.
type ServiceFunctionChainNamespaceListerExpansion interface{}

// ServiceRouteListerExpansion allows custom methods to be added to
// ServiceRouteLister.
type ServiceRouteListerExpansion interface{}

// ServiceRouteNamespaceListerExpansion allows custom methods to be added to
// ServiceRouteNamespaceLister.
type ServiceRouteNamespaceListerExpansion interface{}

// SiteResourceGroupListerExpansion allows custom methods to be added to
// SiteResourceGroupLister.
type SiteResourceGroupListerExpansion interface{}

// SiteResourceGroupNamespaceListerExpansion allows custom methods to be added to
// SiteResourceGroupNamespaceLister.
type SiteResourceGroupNamespaceListerExpansion interface{}
