// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IPSecVpnTunnelLister helps list IPSecVpnTunnels.
type IPSecVpnTunnelLister interface {
	// List lists all IPSecVpnTunnels in the indexer.
	List(selector labels.Selector) (ret []*v1.IPSecVpnTunnel, err error)
	// IPSecVpnTunnels returns an object that can list and get IPSecVpnTunnels.
	IPSecVpnTunnels(namespace string) IPSecVpnTunnelNamespaceLister
	IPSecVpnTunnelListerExpansion
}

// iPSecVpnTunnelLister implements the IPSecVpnTunnelLister interface.
type iPSecVpnTunnelLister struct {
	indexer cache.Indexer
}

// NewIPSecVpnTunnelLister returns a new IPSecVpnTunnelLister.
func NewIPSecVpnTunnelLister(indexer cache.Indexer) IPSecVpnTunnelLister {
	return &iPSecVpnTunnelLister{indexer: indexer}
}

// List lists all IPSecVpnTunnels in the indexer.
func (s *iPSecVpnTunnelLister) List(selector labels.Selector) (ret []*v1.IPSecVpnTunnel, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.IPSecVpnTunnel))
	})
	return ret, err
}

// IPSecVpnTunnels returns an object that can list and get IPSecVpnTunnels.
func (s *iPSecVpnTunnelLister) IPSecVpnTunnels(namespace string) IPSecVpnTunnelNamespaceLister {
	return iPSecVpnTunnelNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// IPSecVpnTunnelNamespaceLister helps list and get IPSecVpnTunnels.
type IPSecVpnTunnelNamespaceLister interface {
	// List lists all IPSecVpnTunnels in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.IPSecVpnTunnel, err error)
	// Get retrieves the IPSecVpnTunnel from the indexer for a given namespace and name.
	Get(name string) (*v1.IPSecVpnTunnel, error)
	IPSecVpnTunnelNamespaceListerExpansion
}

// iPSecVpnTunnelNamespaceLister implements the IPSecVpnTunnelNamespaceLister
// interface.
type iPSecVpnTunnelNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all IPSecVpnTunnels in the indexer for a given namespace.
func (s iPSecVpnTunnelNamespaceLister) List(selector labels.Selector) (ret []*v1.IPSecVpnTunnel, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.IPSecVpnTunnel))
	})
	return ret, err
}

// Get retrieves the IPSecVpnTunnel from the indexer for a given namespace and name.
func (s iPSecVpnTunnelNamespaceLister) Get(name string) (*v1.IPSecVpnTunnel, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("ipsecvpntunnel"), name)
	}
	return obj.(*v1.IPSecVpnTunnel), nil
}
