// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NetworkFirewallProfileLister helps list NetworkFirewallProfiles.
type NetworkFirewallProfileLister interface {
	// List lists all NetworkFirewallProfiles in the indexer.
	List(selector labels.Selector) (ret []*v1.NetworkFirewallProfile, err error)
	// NetworkFirewallProfiles returns an object that can list and get NetworkFirewallProfiles.
	NetworkFirewallProfiles(namespace string) NetworkFirewallProfileNamespaceLister
	NetworkFirewallProfileListerExpansion
}

// networkFirewallProfileLister implements the NetworkFirewallProfileLister interface.
type networkFirewallProfileLister struct {
	indexer cache.Indexer
}

// NewNetworkFirewallProfileLister returns a new NetworkFirewallProfileLister.
func NewNetworkFirewallProfileLister(indexer cache.Indexer) NetworkFirewallProfileLister {
	return &networkFirewallProfileLister{indexer: indexer}
}

// List lists all NetworkFirewallProfiles in the indexer.
func (s *networkFirewallProfileLister) List(selector labels.Selector) (ret []*v1.NetworkFirewallProfile, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.NetworkFirewallProfile))
	})
	return ret, err
}

// NetworkFirewallProfiles returns an object that can list and get NetworkFirewallProfiles.
func (s *networkFirewallProfileLister) NetworkFirewallProfiles(namespace string) NetworkFirewallProfileNamespaceLister {
	return networkFirewallProfileNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// NetworkFirewallProfileNamespaceLister helps list and get NetworkFirewallProfiles.
type NetworkFirewallProfileNamespaceLister interface {
	// List lists all NetworkFirewallProfiles in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.NetworkFirewallProfile, err error)
	// Get retrieves the NetworkFirewallProfile from the indexer for a given namespace and name.
	Get(name string) (*v1.NetworkFirewallProfile, error)
	NetworkFirewallProfileNamespaceListerExpansion
}

// networkFirewallProfileNamespaceLister implements the NetworkFirewallProfileNamespaceLister
// interface.
type networkFirewallProfileNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all NetworkFirewallProfiles in the indexer for a given namespace.
func (s networkFirewallProfileNamespaceLister) List(selector labels.Selector) (ret []*v1.NetworkFirewallProfile, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.NetworkFirewallProfile))
	})
	return ret, err
}

// Get retrieves the NetworkFirewallProfile from the indexer for a given namespace and name.
func (s networkFirewallProfileNamespaceLister) Get(name string) (*v1.NetworkFirewallProfile, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("networkfirewallprofile"), name)
	}
	return obj.(*v1.NetworkFirewallProfile), nil
}
