// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SiteResourceGroupLister helps list SiteResourceGroups.
type SiteResourceGroupLister interface {
	// List lists all SiteResourceGroups in the indexer.
	List(selector labels.Selector) (ret []*v1.SiteResourceGroup, err error)
	// SiteResourceGroups returns an object that can list and get SiteResourceGroups.
	SiteResourceGroups(namespace string) SiteResourceGroupNamespaceLister
	SiteResourceGroupListerExpansion
}

// siteResourceGroupLister implements the SiteResourceGroupLister interface.
type siteResourceGroupLister struct {
	indexer cache.Indexer
}

// NewSiteResourceGroupLister returns a new SiteResourceGroupLister.
func NewSiteResourceGroupLister(indexer cache.Indexer) SiteResourceGroupLister {
	return &siteResourceGroupLister{indexer: indexer}
}

// List lists all SiteResourceGroups in the indexer.
func (s *siteResourceGroupLister) List(selector labels.Selector) (ret []*v1.SiteResourceGroup, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.SiteResourceGroup))
	})
	return ret, err
}

// SiteResourceGroups returns an object that can list and get SiteResourceGroups.
func (s *siteResourceGroupLister) SiteResourceGroups(namespace string) SiteResourceGroupNamespaceLister {
	return siteResourceGroupNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// SiteResourceGroupNamespaceLister helps list and get SiteResourceGroups.
type SiteResourceGroupNamespaceLister interface {
	// List lists all SiteResourceGroups in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.SiteResourceGroup, err error)
	// Get retrieves the SiteResourceGroup from the indexer for a given namespace and name.
	Get(name string) (*v1.SiteResourceGroup, error)
	SiteResourceGroupNamespaceListerExpansion
}

// siteResourceGroupNamespaceLister implements the SiteResourceGroupNamespaceLister
// interface.
type siteResourceGroupNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all SiteResourceGroups in the indexer for a given namespace.
func (s siteResourceGroupNamespaceLister) List(selector labels.Selector) (ret []*v1.SiteResourceGroup, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.SiteResourceGroup))
	})
	return ret, err
}

// Get retrieves the SiteResourceGroup from the indexer for a given namespace and name.
func (s siteResourceGroupNamespaceLister) Get(name string) (*v1.SiteResourceGroup, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("siteresourcegroup"), name)
	}
	return obj.(*v1.SiteResourceGroup), nil
}
