// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SrConfigurationLister helps list SrConfigurations.
type SrConfigurationLister interface {
	// List lists all SrConfigurations in the indexer.
	List(selector labels.Selector) (ret []*v1.SrConfiguration, err error)
	// SrConfigurations returns an object that can list and get SrConfigurations.
	SrConfigurations(namespace string) SrConfigurationNamespaceLister
	SrConfigurationListerExpansion
}

// srConfigurationLister implements the SrConfigurationLister interface.
type srConfigurationLister struct {
	indexer cache.Indexer
}

// NewSrConfigurationLister returns a new SrConfigurationLister.
func NewSrConfigurationLister(indexer cache.Indexer) SrConfigurationLister {
	return &srConfigurationLister{indexer: indexer}
}

// List lists all SrConfigurations in the indexer.
func (s *srConfigurationLister) List(selector labels.Selector) (ret []*v1.SrConfiguration, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.SrConfiguration))
	})
	return ret, err
}

// SrConfigurations returns an object that can list and get SrConfigurations.
func (s *srConfigurationLister) SrConfigurations(namespace string) SrConfigurationNamespaceLister {
	return srConfigurationNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// SrConfigurationNamespaceLister helps list and get SrConfigurations.
type SrConfigurationNamespaceLister interface {
	// List lists all SrConfigurations in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.SrConfiguration, err error)
	// Get retrieves the SrConfiguration from the indexer for a given namespace and name.
	Get(name string) (*v1.SrConfiguration, error)
	SrConfigurationNamespaceListerExpansion
}

// srConfigurationNamespaceLister implements the SrConfigurationNamespaceLister
// interface.
type srConfigurationNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all SrConfigurations in the indexer for a given namespace.
func (s srConfigurationNamespaceLister) List(selector labels.Selector) (ret []*v1.SrConfiguration, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.SrConfiguration))
	})
	return ret, err
}

// Get retrieves the SrConfiguration from the indexer for a given namespace and name.
func (s srConfigurationNamespaceLister) Get(name string) (*v1.SrConfiguration, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("srconfiguration"), name)
	}
	return obj.(*v1.SrConfiguration), nil
}
