// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	contivppiov1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkFirewallProfiles implements NetworkFirewallProfileInterface
type FakeNetworkFirewallProfiles struct {
	Fake *FakeContivppV1
	ns   string
}

var networkfirewallprofilesResource = schema.GroupVersionResource{Group: "contivpp.io", Version: "v1", Resource: "networkfirewallprofiles"}

var networkfirewallprofilesKind = schema.GroupVersionKind{Group: "contivpp.io", Version: "v1", Kind: "NetworkFirewallProfile"}

// Get takes name of the networkFirewallProfile, and returns the corresponding networkFirewallProfile object, and an error if there is any.
func (c *FakeNetworkFirewallProfiles) Get(name string, options v1.GetOptions) (result *contivppiov1.NetworkFirewallProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(networkfirewallprofilesResource, c.ns, name), &contivppiov1.NetworkFirewallProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.NetworkFirewallProfile), err
}

// List takes label and field selectors, and returns the list of NetworkFirewallProfiles that match those selectors.
func (c *FakeNetworkFirewallProfiles) List(opts v1.ListOptions) (result *contivppiov1.NetworkFirewallProfileList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(networkfirewallprofilesResource, networkfirewallprofilesKind, c.ns, opts), &contivppiov1.NetworkFirewallProfileList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &contivppiov1.NetworkFirewallProfileList{ListMeta: obj.(*contivppiov1.NetworkFirewallProfileList).ListMeta}
	for _, item := range obj.(*contivppiov1.NetworkFirewallProfileList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkFirewallProfiles.
func (c *FakeNetworkFirewallProfiles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(networkfirewallprofilesResource, c.ns, opts))

}

// Create takes the representation of a networkFirewallProfile and creates it.  Returns the server's representation of the networkFirewallProfile, and an error, if there is any.
func (c *FakeNetworkFirewallProfiles) Create(networkFirewallProfile *contivppiov1.NetworkFirewallProfile) (result *contivppiov1.NetworkFirewallProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(networkfirewallprofilesResource, c.ns, networkFirewallProfile), &contivppiov1.NetworkFirewallProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.NetworkFirewallProfile), err
}

// Update takes the representation of a networkFirewallProfile and updates it. Returns the server's representation of the networkFirewallProfile, and an error, if there is any.
func (c *FakeNetworkFirewallProfiles) Update(networkFirewallProfile *contivppiov1.NetworkFirewallProfile) (result *contivppiov1.NetworkFirewallProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(networkfirewallprofilesResource, c.ns, networkFirewallProfile), &contivppiov1.NetworkFirewallProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.NetworkFirewallProfile), err
}

// Delete takes name of the networkFirewallProfile and deletes it. Returns an error if one occurs.
func (c *FakeNetworkFirewallProfiles) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(networkfirewallprofilesResource, c.ns, name), &contivppiov1.NetworkFirewallProfile{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkFirewallProfiles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(networkfirewallprofilesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &contivppiov1.NetworkFirewallProfileList{})
	return err
}

// Patch applies the patch and returns the patched networkFirewallProfile.
func (c *FakeNetworkFirewallProfiles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *contivppiov1.NetworkFirewallProfile, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkfirewallprofilesResource, c.ns, name, pt, data, subresources...), &contivppiov1.NetworkFirewallProfile{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.NetworkFirewallProfile), err
}
