// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	contivppiov1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSaseServiceInterfaces implements SaseServiceInterfaceInterface
type FakeSaseServiceInterfaces struct {
	Fake *FakeContivppV1
	ns   string
}

var saseserviceinterfacesResource = schema.GroupVersionResource{Group: "contivpp.io", Version: "v1", Resource: "saseserviceinterfaces"}

var saseserviceinterfacesKind = schema.GroupVersionKind{Group: "contivpp.io", Version: "v1", Kind: "SaseServiceInterface"}

// Get takes name of the saseServiceInterface, and returns the corresponding saseServiceInterface object, and an error if there is any.
func (c *FakeSaseServiceInterfaces) Get(name string, options v1.GetOptions) (result *contivppiov1.SaseServiceInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(saseserviceinterfacesResource, c.ns, name), &contivppiov1.SaseServiceInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SaseServiceInterface), err
}

// List takes label and field selectors, and returns the list of SaseServiceInterfaces that match those selectors.
func (c *FakeSaseServiceInterfaces) List(opts v1.ListOptions) (result *contivppiov1.SaseServiceInterfaceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(saseserviceinterfacesResource, saseserviceinterfacesKind, c.ns, opts), &contivppiov1.SaseServiceInterfaceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &contivppiov1.SaseServiceInterfaceList{ListMeta: obj.(*contivppiov1.SaseServiceInterfaceList).ListMeta}
	for _, item := range obj.(*contivppiov1.SaseServiceInterfaceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested saseServiceInterfaces.
func (c *FakeSaseServiceInterfaces) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(saseserviceinterfacesResource, c.ns, opts))

}

// Create takes the representation of a saseServiceInterface and creates it.  Returns the server's representation of the saseServiceInterface, and an error, if there is any.
func (c *FakeSaseServiceInterfaces) Create(saseServiceInterface *contivppiov1.SaseServiceInterface) (result *contivppiov1.SaseServiceInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(saseserviceinterfacesResource, c.ns, saseServiceInterface), &contivppiov1.SaseServiceInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SaseServiceInterface), err
}

// Update takes the representation of a saseServiceInterface and updates it. Returns the server's representation of the saseServiceInterface, and an error, if there is any.
func (c *FakeSaseServiceInterfaces) Update(saseServiceInterface *contivppiov1.SaseServiceInterface) (result *contivppiov1.SaseServiceInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(saseserviceinterfacesResource, c.ns, saseServiceInterface), &contivppiov1.SaseServiceInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SaseServiceInterface), err
}

// Delete takes name of the saseServiceInterface and deletes it. Returns an error if one occurs.
func (c *FakeSaseServiceInterfaces) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(saseserviceinterfacesResource, c.ns, name), &contivppiov1.SaseServiceInterface{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSaseServiceInterfaces) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(saseserviceinterfacesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &contivppiov1.SaseServiceInterfaceList{})
	return err
}

// Patch applies the patch and returns the patched saseServiceInterface.
func (c *FakeSaseServiceInterfaces) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *contivppiov1.SaseServiceInterface, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(saseserviceinterfacesResource, c.ns, name, pt, data, subresources...), &contivppiov1.SaseServiceInterface{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SaseServiceInterface), err
}
