// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	contivppiov1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSaseSecurityAssociations implements SaseSecurityAssociationInterface
type FakeSaseSecurityAssociations struct {
	Fake *FakeContivppV1
	ns   string
}

var sasesecurityassociationsResource = schema.GroupVersionResource{Group: "contivpp.io", Version: "v1", Resource: "sasesecurityassociations"}

var sasesecurityassociationsKind = schema.GroupVersionKind{Group: "contivpp.io", Version: "v1", Kind: "SaseSecurityAssociation"}

// Get takes name of the saseSecurityAssociation, and returns the corresponding saseSecurityAssociation object, and an error if there is any.
func (c *FakeSaseSecurityAssociations) Get(name string, options v1.GetOptions) (result *contivppiov1.SaseSecurityAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sasesecurityassociationsResource, c.ns, name), &contivppiov1.SaseSecurityAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SaseSecurityAssociation), err
}

// List takes label and field selectors, and returns the list of SaseSecurityAssociations that match those selectors.
func (c *FakeSaseSecurityAssociations) List(opts v1.ListOptions) (result *contivppiov1.SaseSecurityAssociationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sasesecurityassociationsResource, sasesecurityassociationsKind, c.ns, opts), &contivppiov1.SaseSecurityAssociationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &contivppiov1.SaseSecurityAssociationList{ListMeta: obj.(*contivppiov1.SaseSecurityAssociationList).ListMeta}
	for _, item := range obj.(*contivppiov1.SaseSecurityAssociationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested saseSecurityAssociations.
func (c *FakeSaseSecurityAssociations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sasesecurityassociationsResource, c.ns, opts))

}

// Create takes the representation of a saseSecurityAssociation and creates it.  Returns the server's representation of the saseSecurityAssociation, and an error, if there is any.
func (c *FakeSaseSecurityAssociations) Create(saseSecurityAssociation *contivppiov1.SaseSecurityAssociation) (result *contivppiov1.SaseSecurityAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sasesecurityassociationsResource, c.ns, saseSecurityAssociation), &contivppiov1.SaseSecurityAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SaseSecurityAssociation), err
}

// Update takes the representation of a saseSecurityAssociation and updates it. Returns the server's representation of the saseSecurityAssociation, and an error, if there is any.
func (c *FakeSaseSecurityAssociations) Update(saseSecurityAssociation *contivppiov1.SaseSecurityAssociation) (result *contivppiov1.SaseSecurityAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sasesecurityassociationsResource, c.ns, saseSecurityAssociation), &contivppiov1.SaseSecurityAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SaseSecurityAssociation), err
}

// Delete takes name of the saseSecurityAssociation and deletes it. Returns an error if one occurs.
func (c *FakeSaseSecurityAssociations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sasesecurityassociationsResource, c.ns, name), &contivppiov1.SaseSecurityAssociation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSaseSecurityAssociations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sasesecurityassociationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &contivppiov1.SaseSecurityAssociationList{})
	return err
}

// Patch applies the patch and returns the patched saseSecurityAssociation.
func (c *FakeSaseSecurityAssociations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *contivppiov1.SaseSecurityAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sasesecurityassociationsResource, c.ns, name, pt, data, subresources...), &contivppiov1.SaseSecurityAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SaseSecurityAssociation), err
}
