// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	contivppiov1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServiceRoutes implements ServiceRouteInterface
type FakeServiceRoutes struct {
	Fake *FakeContivppV1
	ns   string
}

var serviceroutesResource = schema.GroupVersionResource{Group: "contivpp.io", Version: "v1", Resource: "serviceroutes"}

var serviceroutesKind = schema.GroupVersionKind{Group: "contivpp.io", Version: "v1", Kind: "ServiceRoute"}

// Get takes name of the serviceRoute, and returns the corresponding serviceRoute object, and an error if there is any.
func (c *FakeServiceRoutes) Get(name string, options v1.GetOptions) (result *contivppiov1.ServiceRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(serviceroutesResource, c.ns, name), &contivppiov1.ServiceRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.ServiceRoute), err
}

// List takes label and field selectors, and returns the list of ServiceRoutes that match those selectors.
func (c *FakeServiceRoutes) List(opts v1.ListOptions) (result *contivppiov1.ServiceRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(serviceroutesResource, serviceroutesKind, c.ns, opts), &contivppiov1.ServiceRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &contivppiov1.ServiceRouteList{ListMeta: obj.(*contivppiov1.ServiceRouteList).ListMeta}
	for _, item := range obj.(*contivppiov1.ServiceRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceRoutes.
func (c *FakeServiceRoutes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(serviceroutesResource, c.ns, opts))

}

// Create takes the representation of a serviceRoute and creates it.  Returns the server's representation of the serviceRoute, and an error, if there is any.
func (c *FakeServiceRoutes) Create(serviceRoute *contivppiov1.ServiceRoute) (result *contivppiov1.ServiceRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(serviceroutesResource, c.ns, serviceRoute), &contivppiov1.ServiceRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.ServiceRoute), err
}

// Update takes the representation of a serviceRoute and updates it. Returns the server's representation of the serviceRoute, and an error, if there is any.
func (c *FakeServiceRoutes) Update(serviceRoute *contivppiov1.ServiceRoute) (result *contivppiov1.ServiceRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(serviceroutesResource, c.ns, serviceRoute), &contivppiov1.ServiceRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.ServiceRoute), err
}

// Delete takes name of the serviceRoute and deletes it. Returns an error if one occurs.
func (c *FakeServiceRoutes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(serviceroutesResource, c.ns, name), &contivppiov1.ServiceRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceRoutes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(serviceroutesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &contivppiov1.ServiceRouteList{})
	return err
}

// Patch applies the patch and returns the patched serviceRoute.
func (c *FakeServiceRoutes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *contivppiov1.ServiceRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(serviceroutesResource, c.ns, name, pt, data, subresources...), &contivppiov1.ServiceRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.ServiceRoute), err
}
