// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	contivppiov1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSecurityAssociations implements SecurityAssociationInterface
type FakeSecurityAssociations struct {
	Fake *FakeContivppV1
	ns   string
}

var securityassociationsResource = schema.GroupVersionResource{Group: "contivpp.io", Version: "v1", Resource: "securityassociations"}

var securityassociationsKind = schema.GroupVersionKind{Group: "contivpp.io", Version: "v1", Kind: "SecurityAssociation"}

// Get takes name of the securityAssociation, and returns the corresponding securityAssociation object, and an error if there is any.
func (c *FakeSecurityAssociations) Get(name string, options v1.GetOptions) (result *contivppiov1.SecurityAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(securityassociationsResource, c.ns, name), &contivppiov1.SecurityAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SecurityAssociation), err
}

// List takes label and field selectors, and returns the list of SecurityAssociations that match those selectors.
func (c *FakeSecurityAssociations) List(opts v1.ListOptions) (result *contivppiov1.SecurityAssociationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(securityassociationsResource, securityassociationsKind, c.ns, opts), &contivppiov1.SecurityAssociationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &contivppiov1.SecurityAssociationList{ListMeta: obj.(*contivppiov1.SecurityAssociationList).ListMeta}
	for _, item := range obj.(*contivppiov1.SecurityAssociationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested securityAssociations.
func (c *FakeSecurityAssociations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(securityassociationsResource, c.ns, opts))

}

// Create takes the representation of a securityAssociation and creates it.  Returns the server's representation of the securityAssociation, and an error, if there is any.
func (c *FakeSecurityAssociations) Create(securityAssociation *contivppiov1.SecurityAssociation) (result *contivppiov1.SecurityAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(securityassociationsResource, c.ns, securityAssociation), &contivppiov1.SecurityAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SecurityAssociation), err
}

// Update takes the representation of a securityAssociation and updates it. Returns the server's representation of the securityAssociation, and an error, if there is any.
func (c *FakeSecurityAssociations) Update(securityAssociation *contivppiov1.SecurityAssociation) (result *contivppiov1.SecurityAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(securityassociationsResource, c.ns, securityAssociation), &contivppiov1.SecurityAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SecurityAssociation), err
}

// Delete takes name of the securityAssociation and deletes it. Returns an error if one occurs.
func (c *FakeSecurityAssociations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(securityassociationsResource, c.ns, name), &contivppiov1.SecurityAssociation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecurityAssociations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(securityassociationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &contivppiov1.SecurityAssociationList{})
	return err
}

// Patch applies the patch and returns the patched securityAssociation.
func (c *FakeSecurityAssociations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *contivppiov1.SecurityAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(securityassociationsResource, c.ns, name, pt, data, subresources...), &contivppiov1.SecurityAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SecurityAssociation), err
}
