// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	contivppiov1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSaseServicePolicies implements SaseServicePolicyInterface
type FakeSaseServicePolicies struct {
	Fake *FakeContivppV1
	ns   string
}

var saseservicepoliciesResource = schema.GroupVersionResource{Group: "contivpp.io", Version: "v1", Resource: "saseservicepolicies"}

var saseservicepoliciesKind = schema.GroupVersionKind{Group: "contivpp.io", Version: "v1", Kind: "SaseServicePolicy"}

// Get takes name of the saseServicePolicy, and returns the corresponding saseServicePolicy object, and an error if there is any.
func (c *FakeSaseServicePolicies) Get(name string, options v1.GetOptions) (result *contivppiov1.SaseServicePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(saseservicepoliciesResource, c.ns, name), &contivppiov1.SaseServicePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SaseServicePolicy), err
}

// List takes label and field selectors, and returns the list of SaseServicePolicies that match those selectors.
func (c *FakeSaseServicePolicies) List(opts v1.ListOptions) (result *contivppiov1.SaseServicePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(saseservicepoliciesResource, saseservicepoliciesKind, c.ns, opts), &contivppiov1.SaseServicePolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &contivppiov1.SaseServicePolicyList{ListMeta: obj.(*contivppiov1.SaseServicePolicyList).ListMeta}
	for _, item := range obj.(*contivppiov1.SaseServicePolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested saseServicePolicies.
func (c *FakeSaseServicePolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(saseservicepoliciesResource, c.ns, opts))

}

// Create takes the representation of a saseServicePolicy and creates it.  Returns the server's representation of the saseServicePolicy, and an error, if there is any.
func (c *FakeSaseServicePolicies) Create(saseServicePolicy *contivppiov1.SaseServicePolicy) (result *contivppiov1.SaseServicePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(saseservicepoliciesResource, c.ns, saseServicePolicy), &contivppiov1.SaseServicePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SaseServicePolicy), err
}

// Update takes the representation of a saseServicePolicy and updates it. Returns the server's representation of the saseServicePolicy, and an error, if there is any.
func (c *FakeSaseServicePolicies) Update(saseServicePolicy *contivppiov1.SaseServicePolicy) (result *contivppiov1.SaseServicePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(saseservicepoliciesResource, c.ns, saseServicePolicy), &contivppiov1.SaseServicePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SaseServicePolicy), err
}

// Delete takes name of the saseServicePolicy and deletes it. Returns an error if one occurs.
func (c *FakeSaseServicePolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(saseservicepoliciesResource, c.ns, name), &contivppiov1.SaseServicePolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSaseServicePolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(saseservicepoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &contivppiov1.SaseServicePolicyList{})
	return err
}

// Patch applies the patch and returns the patched saseServicePolicy.
func (c *FakeSaseServicePolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *contivppiov1.SaseServicePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(saseservicepoliciesResource, c.ns, name, pt, data, subresources...), &contivppiov1.SaseServicePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.SaseServicePolicy), err
}
