// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	scheme "github.com/contiv/vpp/plugins/crd/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IPSecVpnTunnelsGetter has a method to return a IPSecVpnTunnelInterface.
// A group's client should implement this interface.
type IPSecVpnTunnelsGetter interface {
	IPSecVpnTunnels(namespace string) IPSecVpnTunnelInterface
}

// IPSecVpnTunnelInterface has methods to work with IPSecVpnTunnel resources.
type IPSecVpnTunnelInterface interface {
	Create(*v1.IPSecVpnTunnel) (*v1.IPSecVpnTunnel, error)
	Update(*v1.IPSecVpnTunnel) (*v1.IPSecVpnTunnel, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.IPSecVpnTunnel, error)
	List(opts metav1.ListOptions) (*v1.IPSecVpnTunnelList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.IPSecVpnTunnel, err error)
	IPSecVpnTunnelExpansion
}

// iPSecVpnTunnels implements IPSecVpnTunnelInterface
type iPSecVpnTunnels struct {
	client rest.Interface
	ns     string
}

// newIPSecVpnTunnels returns a IPSecVpnTunnels
func newIPSecVpnTunnels(c *ContivppV1Client, namespace string) *iPSecVpnTunnels {
	return &iPSecVpnTunnels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the iPSecVpnTunnel, and returns the corresponding iPSecVpnTunnel object, and an error if there is any.
func (c *iPSecVpnTunnels) Get(name string, options metav1.GetOptions) (result *v1.IPSecVpnTunnel, err error) {
	result = &v1.IPSecVpnTunnel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ipsecvpntunnels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IPSecVpnTunnels that match those selectors.
func (c *iPSecVpnTunnels) List(opts metav1.ListOptions) (result *v1.IPSecVpnTunnelList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.IPSecVpnTunnelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ipsecvpntunnels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested iPSecVpnTunnels.
func (c *iPSecVpnTunnels) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ipsecvpntunnels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a iPSecVpnTunnel and creates it.  Returns the server's representation of the iPSecVpnTunnel, and an error, if there is any.
func (c *iPSecVpnTunnels) Create(iPSecVpnTunnel *v1.IPSecVpnTunnel) (result *v1.IPSecVpnTunnel, err error) {
	result = &v1.IPSecVpnTunnel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ipsecvpntunnels").
		Body(iPSecVpnTunnel).
		Do().
		Into(result)
	return
}

// Update takes the representation of a iPSecVpnTunnel and updates it. Returns the server's representation of the iPSecVpnTunnel, and an error, if there is any.
func (c *iPSecVpnTunnels) Update(iPSecVpnTunnel *v1.IPSecVpnTunnel) (result *v1.IPSecVpnTunnel, err error) {
	result = &v1.IPSecVpnTunnel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ipsecvpntunnels").
		Name(iPSecVpnTunnel.Name).
		Body(iPSecVpnTunnel).
		Do().
		Into(result)
	return
}

// Delete takes name of the iPSecVpnTunnel and deletes it. Returns an error if one occurs.
func (c *iPSecVpnTunnels) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ipsecvpntunnels").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *iPSecVpnTunnels) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ipsecvpntunnels").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched iPSecVpnTunnel.
func (c *iPSecVpnTunnels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.IPSecVpnTunnel, err error) {
	result = &v1.IPSecVpnTunnel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ipsecvpntunnels").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
