// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	scheme "github.com/contiv/vpp/plugins/crd/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetworkFirewallProfilesGetter has a method to return a NetworkFirewallProfileInterface.
// A group's client should implement this interface.
type NetworkFirewallProfilesGetter interface {
	NetworkFirewallProfiles(namespace string) NetworkFirewallProfileInterface
}

// NetworkFirewallProfileInterface has methods to work with NetworkFirewallProfile resources.
type NetworkFirewallProfileInterface interface {
	Create(*v1.NetworkFirewallProfile) (*v1.NetworkFirewallProfile, error)
	Update(*v1.NetworkFirewallProfile) (*v1.NetworkFirewallProfile, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.NetworkFirewallProfile, error)
	List(opts metav1.ListOptions) (*v1.NetworkFirewallProfileList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NetworkFirewallProfile, err error)
	NetworkFirewallProfileExpansion
}

// networkFirewallProfiles implements NetworkFirewallProfileInterface
type networkFirewallProfiles struct {
	client rest.Interface
	ns     string
}

// newNetworkFirewallProfiles returns a NetworkFirewallProfiles
func newNetworkFirewallProfiles(c *ContivppV1Client, namespace string) *networkFirewallProfiles {
	return &networkFirewallProfiles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the networkFirewallProfile, and returns the corresponding networkFirewallProfile object, and an error if there is any.
func (c *networkFirewallProfiles) Get(name string, options metav1.GetOptions) (result *v1.NetworkFirewallProfile, err error) {
	result = &v1.NetworkFirewallProfile{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networkfirewallprofiles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetworkFirewallProfiles that match those selectors.
func (c *networkFirewallProfiles) List(opts metav1.ListOptions) (result *v1.NetworkFirewallProfileList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NetworkFirewallProfileList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networkfirewallprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested networkFirewallProfiles.
func (c *networkFirewallProfiles) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("networkfirewallprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a networkFirewallProfile and creates it.  Returns the server's representation of the networkFirewallProfile, and an error, if there is any.
func (c *networkFirewallProfiles) Create(networkFirewallProfile *v1.NetworkFirewallProfile) (result *v1.NetworkFirewallProfile, err error) {
	result = &v1.NetworkFirewallProfile{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("networkfirewallprofiles").
		Body(networkFirewallProfile).
		Do().
		Into(result)
	return
}

// Update takes the representation of a networkFirewallProfile and updates it. Returns the server's representation of the networkFirewallProfile, and an error, if there is any.
func (c *networkFirewallProfiles) Update(networkFirewallProfile *v1.NetworkFirewallProfile) (result *v1.NetworkFirewallProfile, err error) {
	result = &v1.NetworkFirewallProfile{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("networkfirewallprofiles").
		Name(networkFirewallProfile.Name).
		Body(networkFirewallProfile).
		Do().
		Into(result)
	return
}

// Delete takes name of the networkFirewallProfile and deletes it. Returns an error if one occurs.
func (c *networkFirewallProfiles) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networkfirewallprofiles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *networkFirewallProfiles) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networkfirewallprofiles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched networkFirewallProfile.
func (c *networkFirewallProfiles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NetworkFirewallProfile, err error) {
	result = &v1.NetworkFirewallProfile{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("networkfirewallprofiles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
