// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	scheme "github.com/contiv/vpp/plugins/crd/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SaseSecurityAssociationsGetter has a method to return a SaseSecurityAssociationInterface.
// A group's client should implement this interface.
type SaseSecurityAssociationsGetter interface {
	SaseSecurityAssociations(namespace string) SaseSecurityAssociationInterface
}

// SaseSecurityAssociationInterface has methods to work with SaseSecurityAssociation resources.
type SaseSecurityAssociationInterface interface {
	Create(*v1.SaseSecurityAssociation) (*v1.SaseSecurityAssociation, error)
	Update(*v1.SaseSecurityAssociation) (*v1.SaseSecurityAssociation, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.SaseSecurityAssociation, error)
	List(opts metav1.ListOptions) (*v1.SaseSecurityAssociationList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SaseSecurityAssociation, err error)
	SaseSecurityAssociationExpansion
}

// saseSecurityAssociations implements SaseSecurityAssociationInterface
type saseSecurityAssociations struct {
	client rest.Interface
	ns     string
}

// newSaseSecurityAssociations returns a SaseSecurityAssociations
func newSaseSecurityAssociations(c *ContivppV1Client, namespace string) *saseSecurityAssociations {
	return &saseSecurityAssociations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the saseSecurityAssociation, and returns the corresponding saseSecurityAssociation object, and an error if there is any.
func (c *saseSecurityAssociations) Get(name string, options metav1.GetOptions) (result *v1.SaseSecurityAssociation, err error) {
	result = &v1.SaseSecurityAssociation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sasesecurityassociations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SaseSecurityAssociations that match those selectors.
func (c *saseSecurityAssociations) List(opts metav1.ListOptions) (result *v1.SaseSecurityAssociationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SaseSecurityAssociationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sasesecurityassociations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested saseSecurityAssociations.
func (c *saseSecurityAssociations) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sasesecurityassociations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a saseSecurityAssociation and creates it.  Returns the server's representation of the saseSecurityAssociation, and an error, if there is any.
func (c *saseSecurityAssociations) Create(saseSecurityAssociation *v1.SaseSecurityAssociation) (result *v1.SaseSecurityAssociation, err error) {
	result = &v1.SaseSecurityAssociation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sasesecurityassociations").
		Body(saseSecurityAssociation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a saseSecurityAssociation and updates it. Returns the server's representation of the saseSecurityAssociation, and an error, if there is any.
func (c *saseSecurityAssociations) Update(saseSecurityAssociation *v1.SaseSecurityAssociation) (result *v1.SaseSecurityAssociation, err error) {
	result = &v1.SaseSecurityAssociation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sasesecurityassociations").
		Name(saseSecurityAssociation.Name).
		Body(saseSecurityAssociation).
		Do().
		Into(result)
	return
}

// Delete takes name of the saseSecurityAssociation and deletes it. Returns an error if one occurs.
func (c *saseSecurityAssociations) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sasesecurityassociations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *saseSecurityAssociations) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sasesecurityassociations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched saseSecurityAssociation.
func (c *saseSecurityAssociations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SaseSecurityAssociation, err error) {
	result = &v1.SaseSecurityAssociation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sasesecurityassociations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
