// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	scheme "github.com/contiv/vpp/plugins/crd/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SaseServiceInterfacesGetter has a method to return a SaseServiceInterfaceInterface.
// A group's client should implement this interface.
type SaseServiceInterfacesGetter interface {
	SaseServiceInterfaces(namespace string) SaseServiceInterfaceInterface
}

// SaseServiceInterfaceInterface has methods to work with SaseServiceInterface resources.
type SaseServiceInterfaceInterface interface {
	Create(*v1.SaseServiceInterface) (*v1.SaseServiceInterface, error)
	Update(*v1.SaseServiceInterface) (*v1.SaseServiceInterface, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.SaseServiceInterface, error)
	List(opts metav1.ListOptions) (*v1.SaseServiceInterfaceList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SaseServiceInterface, err error)
	SaseServiceInterfaceExpansion
}

// saseServiceInterfaces implements SaseServiceInterfaceInterface
type saseServiceInterfaces struct {
	client rest.Interface
	ns     string
}

// newSaseServiceInterfaces returns a SaseServiceInterfaces
func newSaseServiceInterfaces(c *ContivppV1Client, namespace string) *saseServiceInterfaces {
	return &saseServiceInterfaces{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the saseServiceInterface, and returns the corresponding saseServiceInterface object, and an error if there is any.
func (c *saseServiceInterfaces) Get(name string, options metav1.GetOptions) (result *v1.SaseServiceInterface, err error) {
	result = &v1.SaseServiceInterface{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("saseserviceinterfaces").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SaseServiceInterfaces that match those selectors.
func (c *saseServiceInterfaces) List(opts metav1.ListOptions) (result *v1.SaseServiceInterfaceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SaseServiceInterfaceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("saseserviceinterfaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested saseServiceInterfaces.
func (c *saseServiceInterfaces) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("saseserviceinterfaces").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a saseServiceInterface and creates it.  Returns the server's representation of the saseServiceInterface, and an error, if there is any.
func (c *saseServiceInterfaces) Create(saseServiceInterface *v1.SaseServiceInterface) (result *v1.SaseServiceInterface, err error) {
	result = &v1.SaseServiceInterface{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("saseserviceinterfaces").
		Body(saseServiceInterface).
		Do().
		Into(result)
	return
}

// Update takes the representation of a saseServiceInterface and updates it. Returns the server's representation of the saseServiceInterface, and an error, if there is any.
func (c *saseServiceInterfaces) Update(saseServiceInterface *v1.SaseServiceInterface) (result *v1.SaseServiceInterface, err error) {
	result = &v1.SaseServiceInterface{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("saseserviceinterfaces").
		Name(saseServiceInterface.Name).
		Body(saseServiceInterface).
		Do().
		Into(result)
	return
}

// Delete takes name of the saseServiceInterface and deletes it. Returns an error if one occurs.
func (c *saseServiceInterfaces) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("saseserviceinterfaces").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *saseServiceInterfaces) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("saseserviceinterfaces").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched saseServiceInterface.
func (c *saseServiceInterfaces) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SaseServiceInterface, err error) {
	result = &v1.SaseServiceInterface{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("saseserviceinterfaces").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
