// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	scheme "github.com/contiv/vpp/plugins/crd/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SecurityAssociationsGetter has a method to return a SecurityAssociationInterface.
// A group's client should implement this interface.
type SecurityAssociationsGetter interface {
	SecurityAssociations(namespace string) SecurityAssociationInterface
}

// SecurityAssociationInterface has methods to work with SecurityAssociation resources.
type SecurityAssociationInterface interface {
	Create(*v1.SecurityAssociation) (*v1.SecurityAssociation, error)
	Update(*v1.SecurityAssociation) (*v1.SecurityAssociation, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.SecurityAssociation, error)
	List(opts metav1.ListOptions) (*v1.SecurityAssociationList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SecurityAssociation, err error)
	SecurityAssociationExpansion
}

// securityAssociations implements SecurityAssociationInterface
type securityAssociations struct {
	client rest.Interface
	ns     string
}

// newSecurityAssociations returns a SecurityAssociations
func newSecurityAssociations(c *ContivppV1Client, namespace string) *securityAssociations {
	return &securityAssociations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the securityAssociation, and returns the corresponding securityAssociation object, and an error if there is any.
func (c *securityAssociations) Get(name string, options metav1.GetOptions) (result *v1.SecurityAssociation, err error) {
	result = &v1.SecurityAssociation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("securityassociations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SecurityAssociations that match those selectors.
func (c *securityAssociations) List(opts metav1.ListOptions) (result *v1.SecurityAssociationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SecurityAssociationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("securityassociations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested securityAssociations.
func (c *securityAssociations) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("securityassociations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a securityAssociation and creates it.  Returns the server's representation of the securityAssociation, and an error, if there is any.
func (c *securityAssociations) Create(securityAssociation *v1.SecurityAssociation) (result *v1.SecurityAssociation, err error) {
	result = &v1.SecurityAssociation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("securityassociations").
		Body(securityAssociation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a securityAssociation and updates it. Returns the server's representation of the securityAssociation, and an error, if there is any.
func (c *securityAssociations) Update(securityAssociation *v1.SecurityAssociation) (result *v1.SecurityAssociation, err error) {
	result = &v1.SecurityAssociation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("securityassociations").
		Name(securityAssociation.Name).
		Body(securityAssociation).
		Do().
		Into(result)
	return
}

// Delete takes name of the securityAssociation and deletes it. Returns an error if one occurs.
func (c *securityAssociations) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("securityassociations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *securityAssociations) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("securityassociations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched securityAssociation.
func (c *securityAssociations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SecurityAssociation, err error) {
	result = &v1.SecurityAssociation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("securityassociations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
